//created on: 6 giu 2020
package readyToRock

//list any import classes here.

import readyToRock.Player
import readyToRock.Cards
import java.util.Arrays
import javafx.scene.control.Button
import java.util.Random
import java.io.FileInputStream
import java.io.FileNotFoundException
import javafx.scene.image.Image
import javafx.scene.image.ImageView
//declare any global variables here
dialect "mvel" 






rule "Set initial player position"

    when
    $b: Board()  
    $c: Cards()
    $p: Player(color == "Blue" && cell.getId() == null && $p.cards.size() == 0 )
   	$p2: Player(color != "Blue" && cell.getId() == null)
    then
    
  	 
	$b.setInitialPosition($p,$p2);
	
	for (int i = 0; i < 3; i++) {

			$p.drawCard($c);
		}
		$p2.isTurn = false;
	
        
end

rule "Set initial cpu position"

    when
    $b: Board()  
 	$c: Cards()
 	$p: Player(color == "Blue" )
    $p2: Player(color != "Blue" && cell.getId() == null)
    then
    
  
	$b.setCpuInitialPosition($p2,$p);
	for (int i = 0; i < 3; i++) {

			$p2.drawCard($c);
		}
        
end




rule "Skip one turn"
    //include attributes such as "salience" here...
    when
   $b: Board()
  // $p2: Player(cardToPlay == "")
   $p: Player(cardToPlay == "Ear Plugs" && getActions() > 0) 
   $p2:Player(cardToPlay == "")
    then
	        
	$p2.setActions(0);
	$p.getCards().remove($p.cardToPlay);
	$p.cardToPlay = "";
	$p.setActions($p.getActions()-1);
	
end

rule "Discard two cards"
    //include attributes such as "salience" here...
    when
   $b: Board()
  
   $p: Player(cardToPlay == "Smashed bottle" && getActions() > 0) 
   $p2:Player(cardToPlay == "")
    then
	        
	$p2.getCards().remove(0);
	$p2.getCards().remove(0);
	$p.getCards().remove($p.cardToPlay);
	$p.cardToPlay = "";
	$p.setActions($p.getActions()-1);
	
end

rule "Draw two cards"
    //include attributes such as "salience" here...
    when
        $b: Board()
        $c: Cards()
   		$p: Player(cardToPlay == "Water" && getActions() > 0) 
    then
    
    for(int i=0; i<2; i++){
        $p.drawCard($c);	
			}
			$p.getCards().remove($p.cardToPlay);
			$p.cardToPlay = "";
			$p.setActions($p.getActions()-1);
end

rule "Draw three cards"
    //include attributes such as "salience" here...
    when
        $b: Board()
        $c: Cards()
   		$p: Player(cardToPlay == "Lot of water" && getActions() > 0) 
    then
    
    for(int i=0; i<3; i++){
        $p.drawCard($c);	
			}
			$p.getCards().remove($p.cardToPlay);
			$p.cardToPlay="";
			$p.setActions($p.getActions()-1);
end

rule "Go forward"
    
    when
   $b: Board()
   $p: Player(cardToPlay == "Straight" && getActions() > 0)
   $p2: Player(cardToPlay == "") 
    then
    $p.setCell($p.getTopCell($b),$p2);
    $p.getCards().remove($p.cardToPlay);
    $p.cardToPlay = "";
   // $p.getCards().remove($p.cardToPlay);
    $p.setActions($p.getActions()-1);
       

end

rule "Go forward-right"
    //include attributes such as "salience" here...
    when
   $b: Board()
   $p: Player(cardToPlay == "Turn-right" && getActions() > 0)
    $p2: Player(cardToPlay == "") 
    then
      $p.setCell($p.getTopCell($b),$p2);
      
     $p.getCards().remove($p.cardToPlay);
    $p.cardToPlay = "";
    $p.setActions($p.getActions()-1);

end

rule "Go forward-left"
    //include attributes such as "salience" here...
    when
       $b: Board()
   $p: Player(cardToPlay == "Turn-left" && getActions() > 0)
    $p2: Player(cardToPlay == "") 
    then
        $p.setCell($p.getTopCell($b),$p2);
       $p.getCards().remove($p.cardToPlay);
    $p.cardToPlay = "";
    $p.setActions($p.getActions()-1);

end

rule "Go left"
    //include attributes such as "salience" here...
    when
    $b: Board()
   $p: Player(cardToPlay == "Left/Right" && getActions() > 0 && getPosition()[1] > 3)
    $p2: Player(cardToPlay == "") 
    then
         $p.setCell($p.getLeftCell($b),$p2);
     $p.getCards().remove($p.cardToPlay);
    $p.cardToPlay = "";
    $p.setActions($p.getActions()-1);

end

rule "Go right"
    //include attributes such as "salience" here...
    when
   $b: Board()
   $p: Player(cardToPlay == "Left/Right" && getActions() > 0 && getPosition()[1] < 3 )
    $p2: Player(cardToPlay == "") 
    then
         $p.setCell($p.getRightCell($b),$p2);
       $p.getCards().remove($p.cardToPlay);
    $p.cardToPlay = "";
    $p.setActions($p.getActions()-1);

end

rule "StraightLR"
    //include attributes such as "salience" here...
    when
   $b: Board()
   $p: Player(cardToPlay == "StraightLR" )
    $p2: Player(cardToPlay == "") 
    then
         $p.setCell($p.getTopCell($b),$p2);
      $p.getCards().remove($p.cardToPlay);
    $p.cardToPlay = "";
    $p.setActions($p.getActions()-1);

end

rule "Cross1"
    //include attributes such as "salience" here...
    when
   $b: Board()
   $p: Player(cardToPlay == "Cross" && getActions() > 0 && getPosition()[1] < 3   )
    $p2: Player(cardToPlay == "") 
    then
         $p.setCell($p.getRightCell($b),$p2);
       $p.getCards().remove($p.cardToPlay);
    $p.cardToPlay = "";
    $p.setActions($p.getActions()-1);

end

rule "Cross2"
    //include attributes such as "salience" here...
    when
   $b: Board()
   $p: Player(cardToPlay == "Cross" && getActions() > 0 && getPosition()[1] > 3   )
    $p2: Player(cardToPlay == "") 
    then
         $p.setCell($p.getLeftCell($b),$p2);
       $p.getCards().remove($p.cardToPlay);
    $p.cardToPlay = "";
    $p.setActions($p.getActions()-1);

end

rule "Cross3"
    //include attributes such as "salience" here...
    when
   $b: Board()
   $p: Player(cardToPlay == "Cross" && getActions() > 0 && getPosition()[1] == 3   )
    $p2: Player(cardToPlay == "") 
    then
         $p.setCell($p.getTopCell($b),$p2);
      $p.getCards().remove($p.cardToPlay);
    $p.cardToPlay = "";
    $p.setActions($p.getActions()-1);

end


rule "Set cpu turn"
    //include attributes such as "salience" here...
    when
         $p: Player( cardToPlay == "Finish your turn" )
         $p2: Player(cardToPlay == "")
         
    then
        $p.isTurn = false;
        $p.cardToPlay="";
        $p2.isTurn = true;

end

rule "Draw one card"
    //include attributes such as "salience" here...
    when
   $b: Board()
   $p: Player(cardToPlay == "Draw one card" && getActions() > 0)
   $c: Cards()
 
    then
      $p.drawCard($c);
      $p.cardToPlay= "";
    $p.setActions($p.getActions()-1);

end

rule "Discard one card"
    //include attributes such as "salience" here...
    when
   $b: Board()
   $p: Player(cardToPlay == "Discard one card" && getActions() > 0)
   $c: Cards()
 
    then
      $p.getCards().remove(new Random().nextInt($p.getCards().size()));
      $p.cardToPlay= "";
    $p.setActions($p.getActions()-1);

end

rule "Smashed bottle"
    //include attributes such as "salience" here...
    when
   $b: Board()
   $p: Player(cardToPlay == "Smashed bottle" && getActions() > 0)
   $p2: Player(cardToPlay == "")
    then
      $p2.getCards().remove(new Random().nextInt($p2.getCards().size()));
      $p2.getCards().remove(new Random().nextInt($p2.getCards().size()));
      $p.getCards().remove($p.cardToPlay);
    $p.cardToPlay = "";
    $p.setActions($p.getActions()-1);

end


rule "Cpu turn"
   
    when
   $b: Board()
   $p: Player(color == "Red" && isTurn == true && getActions() > 0 && cardToPlay == "")
   
    then
	$p.cardToPlay = $p.findCardToPlay();
	$p.cpuTurn();

end

rule "Finish cpu turn"
    //include attributes such as "salience" here...
    when
   $b: Board()
   $p: Player(color == "Red" && isTurn == true && getActions() == 0 && cardToPlay == "")
   $p2 : Player(color =="Blue")
    then
    
	$p.isTurn = false;
	$p2.isTurn = true;
	$p2.setActions(2);
	$p.cpuTurn();

end


