//created on: 6 giu 2020
package readyToRock

//list any import classes here.

import readyToRock.Player
import readyToRock.Cards
import java.util.Arrays
import javafx.scene.control.Button
import java.util.Random
import java.io.FileInputStream
import java.io.FileNotFoundException
import javafx.scene.image.Image
import javafx.scene.image.ImageView
//declare any global variables here
dialect "mvel" 






rule "Set initial player position"

    when
    $b: Board()  
    $p: Player(color == "Blue" && cell.getId() == null)
 
    then
    
  	 
	$b.setInitialPosition($p);
	
        
end

rule "Set initial cpu position"

    when
    $b: Board()  
  	$p: Player(color == "Blue" && cell.getId() != null)
    $p2: Player(color != "Blue" && cell.getId() == null)
    then
    
  
	$b.setCpuInitialPosition($p,$p2);
        
end



rule "Draw one card"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end


rule "Skip two turns"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end


rule "Put a wall"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end


rule "Gain two extra actions"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
